pipeline {
    agent any

    options {
        timestamps()
    }

    stages {

        stage('Verify Source') {
            steps {
                echo '=== VERIFY SOURCE ==='

                sh '''
                    test -f school-website/index.html
                    echo "index.html ditemukan"
                '''
            }
        }

        stage('Deploy Staging') {
            steps {
                echo '=== DEPLOY STAGING ==='

                sh '''
                    rsync -rv --delete \
                        --no-perms \
                        --no-owner \
                        --no-group \
                        --omit-dir-times \
                        --exclude='Jenkinsfile' \
                        school-website/ \
                        /var/www/sekolah-staging/
                '''
            }
        }

        stage('Health Check') {
            steps {
                echo '=== HEALTH CHECK ==='

                sh '''
                    curl -fsS \
                        -H "Host: staging.sekolah.local" \
                        http://127.0.0.1/ > /dev/null

                    echo "Website staging UP"
                '''
            }
        }
    }

    post {
        success {
            echo '================================'
            echo 'STAGING DEPLOYMENT SUCCESS'
            echo '================================'
        }

        failure {
            echo '================================'
            echo 'STAGING DEPLOYMENT FAILED'
            echo '================================'
        }
    }
}